### ISSUE TITLE
what is left to do for 1.x release?

### ISSUE THREAD

**Issue by jrobeson** [matthiasnoback/SymfonyConfigTest#15]
I'm just wondering what is left on the agenda before the library is bumped to a 1.x version. This would ease the installation requirements.

**Comment by matthiasnoback** [comment]
Nothing really ;) I was looking for maybe some improvements based on
community feedback but everything seems to be alright. I'll tag 1.0.0 as
soon as I can.
Op 31 jan. 2015 01:18 schreef "Johnny Robeson" <notifications@github.com>:

**Comment by mmoreram** [comment]
This Bundle is really useful (I would like to use it in Elcodi) but there is one basic thing I really miss, and has nothing to do with this bundle itself, and is the wildcard in PHPUnit asserts). Would be nice to test just one block instead of all Tree, and this would make the tests more uncoupled from the implementation, right?

**Comment by matthiasnoback** [comment]
I'm not sure if that would work. You could do it if it's possible to fetch
a specific node from the tree, then use it as root node. At least we could
hack it using reflection but it would be nice to explore our options here.
Op 31 jan. 2015 15:51 schreef "Marc Morera" <notifications@github.com>:

**Comment by matthiasnoback** [comment]
I think that @mmoreram in particular would be interested to try out the new configuration tree branch test feature (by the way "branch" might be good parameter name, instead of "breadcrumbPath" ;)). Just install the "dev-partial_node_testing" version of this library!

**Comment by jrobeson** [comment]
so how's that going? If nothing else, that could be a feature for 2.x

**Comment by mmoreram** [comment]
Yep, @jrobeson sorry about that, so much work for a elcodi release... Next week I will take a look at the feature and I'll give my feedback :)

ping @matthiasnoback

**Comment by matthiasnoback** [comment]
You're right, this could be tagged as 1.0. I have implemented this feature
in a branch but want to change its API first. In my opinion this feature is
really needed to make it more usable. But it can wait until 1.1.
Op 1 mrt. 2015 15:36 schreef "Marc Morera" <notifications@github.com>:

**Comment by matthiasnoback** [comment]
Release 1.0.0 just now...
