### ISSUE TITLE
Tests for partial trees

### ISSUE THREAD

**Issue by matthiasnoback** [matthiasnoback/SymfonyConfigTest#16]
As proposed by @mmoreram this library should offer the ability to partially test a config tree (this is WIP here: https://github.com/matthiasnoback/SymfonyConfigTest/tree/partial_node_testing).

**Comment by matthiasnoback** [comment]
@mmoremam Hi Marc! I've merged this feature into master! See the README: https://github.com/matthiasnoback/SymfonyConfigTest#test-a-subset-of-the-configuration-tree You can use breadcrumb paths at several places to test only specific subnodes of your configuration tree. Would you like test it? Use either dev-master or 2.0.0-beta. By the way, this will be in 2.0 which requires PHP 5.4 and only offers a trait to use in PHPUnit test cases.

**Comment by mmoreram** [comment]
Thanks @matthiasnoback.

Sorry for my no-feedback. I will try to use this project in Elcodi ASAP, during beta stage :)

Good work dude! ^^

**Comment by matthiasnoback** [comment]
No problem at all, anyway, I fixed this in another PR, so that's why closed this issue :)
