### ISSUE TITLE
Composition over inheritance when it comes to adding tests

### ISSUE THREAD

**Issue by iltar** [matthiasnoback/SymfonyConfigTest#17]
Heya!

First of all, I really like this package and makes it a lot easier to test configurations, but I'd like to open this issue anyway. Would it be an option to add a trait that contains the functionality of `AbstractConfigurationTestCase`?  This would make it possible to add the functionality and still be able to extend another test case.

**Comment by matthiasnoback** [comment]
Definitely! I never like this kind of duplication in a code base, but it makes a lot of sense. Would you like to make a PR for this?

**Comment by iltar** [comment]
Yes, I should have some time next week to make a PR. I see there's no minimum PHP version requirement defined, shall I just add a "copy" into a trait and deprecate the abstract class? Considering PHP 5.4 is approaching end of life and is the version it got added to.

**Comment by matthiasnoback** [comment]
Cool! Yes, for now I'd like to offer support for 5.3. You're right about this missing requirement but for me it's important to keep the PHP version requirement in sync with Symfony's requirements. Thank you very much in advance! Once you're done, could you also add a note about it in the README file?

**Comment by WouterJ** [comment]
This can now be closed

**Comment by matthiasnoback** [comment]
@WouterJ thanks for pointing it out :)
