### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by regularjack** [matthiasnoback/SymfonyConfigTest#21]
Could you create a new `v1.1.1` release? I'm in need of using the `$breadcrumbPath` parameter in commit https://github.com/matthiasnoback/SymfonyConfigTest/commit/3ad340c3a54266493734552e17627f998b8d3e95.

Thanks.

**Comment by matthiasnoback** [comment]
I somehow forgot to do that, don't know how it happened. Anyway, the new version is 1.2.0 since it's an extra feature, no bugfix :) Enjoy!

**Comment by regularjack** [comment]
Thanks!
