### ISSUE TITLE
`sebastian/exporter` should be in Composer’s `require`section

### ISSUE THREAD

**Issue by oscherler** [matthiasnoback/SymfonyConfigTest#22]
`sebastian/exporter` is used by `AbstractConfigurationConstraint`, so it should be available. But if it’s in Composer’s `require-dev` section, it’s not installed in projects that require `matthiasnoback/symfony-config-test`.

**Comment by matthiasnoback** [comment]
Good point, please submit a PR which corrects this mistake.

**Comment by oscherler** [comment]
By the way, I’m sorry if I sounded condescending in my writing, I didn’t intend to. I just tried to be concise and accurate.

**Comment by matthiasnoback** [comment]
No problem, I was in no way whatsoever offended :)

Can you provide the fix?
