### ISSUE TITLE
Child node "pagelayout" is not an array node (current path: "netgen_site")

### ISSUE THREAD

**Issue by emodric** [matthiasnoback/SymfonyConfigTest#29]
When testing the following config:

```
$rootNode->children()
    ->scalarNode('pagelayout')
        ->defaultValue('NetgenSiteBundle::empty_pagelayout.html.twig')
        ->cannotBeEmpty()
    ->end();
```

with the following test:

```
$config = array(
    array(
        'pagelayout' => 'pagelayout.html.twig',
    )
);

$expectedConfig = array(
    'pagelayout' => 'pagelayout.html.twig',
);

$this->assertProcessedConfigurationEquals(
    $config,
    $expectedConfig,
    'pagelayout'
);
```

test fails with the following error:

```
1) Netgen\Bundle\SiteBundle\Tests\DependencyInjection\Configuration\PagelayoutConfigurationTest::testPagelayoutSettings
Matthias\SymfonyConfigTest\Partial\Exception\ChildIsNotAnArrayNode: Child node "pagelayout" is not an array node (current path: "netgen_site")

/var/www/html/netgensite/vendor/matthiasnoback/symfony-config-test/Partial/PartialNode.php:46
/var/www/html/netgensite/vendor/matthiasnoback/symfony-config-test/Partial/PartialNode.php:29
/var/www/html/netgensite/vendor/matthiasnoback/symfony-config-test/Partial/PartialProcessor.php:13
/var/www/html/netgensite/vendor/matthiasnoback/symfony-config-test/Partial/PartialProcessor.php:22
/var/www/html/netgensite/vendor/matthiasnoback/symfony-config-test/PhpUnit/AbstractConfigurationConstraint.php:25
/var/www/html/netgensite/vendor/matthiasnoback/symfony-config-test/PhpUnit/ProcessedConfigurationEqualsConstraint.php:24
/var/www/html/netgensite/vendor/matthiasnoback/symfony-config-test/PhpUnit/ConfigurationTestCaseTrait.php:113
/var/www/html/netgensite/src/Netgen/Bundle/SiteBundle/Tests/DependencyInjection/Configuration/PagelayoutConfigurationTest.php:48
```

When I remove the third param from `assertProcessedConfigurationEquals` call, naturally, the test complains because there are other semantic config values in `netgen_site` namespace, which are not excluded.

The only way I can get the test to pass is to remove all of those other configs.

Am I doing something wrong here?

EDIT: Same works fine when the node directly below the root node is an array node.

Thanks!

**Comment by matthiasnoback** [comment]
The error is correct - you can only filter out array nodes if you want to
test part of a configuration tree.

**Comment by emodric** [comment]
Why is that? I can't think of any reason why it shouldn't be possible :)

What is the alternative?

Thanks!

**Comment by matthiasnoback** [comment]
I think you're right that it should be possible, it just isn't :) If you
can come up with a solution - that would be awesome!

On Fri, Nov 20, 2015 at 8:27 PM, Edi Modrić <notifications@github.com>
wrote:

> Why is that? I can't think of any reason why it shouldn't be possible :)
>
> What is the alternative?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthiasnoback/SymfonyConfigTest/issues/29#issuecomment-158501303>
> .
>



-- 
*Noback's Office*
http://nobacksoffice.nl
+31(0)614995363

**Comment by emodric** [comment]
@matthiasnoback Here you go :)

https://github.com/matthiasnoback/SymfonyConfigTest/pull/30
